### ISSUE TITLE
화면구현 - 회원(member) 페이지

### ISSUE THREAD

**Issue by kdg99** [KimDongGeun200418/Kmarket2#6]
- [x] 로그인 : chhak.or.kr/Kmarket/member/login.html
- [x] 회원구분 : chhak.or.kr/Kmarket/member/join.html
- [x] 약관동의 : chhak.or.kr/Kmarket/member/signup.html
- [x] 회원가입 : chhak.or.kr/Kmarket/member/register.html
- [x] 회원가입 : chhak.or.kr/Kmarket/member/registerSeller.html

**Comment by SBUX1992** [comment]
2023-02-07
1. member
 - join / login / signup 완료

**Comment by SBUX1992** [comment]
2023-02-08
1. member
 - 회원가입 / 판매자 회원가입 화면구현 완료
